# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designe_instrument.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 625)
        Form.setStyleSheet("#Form{\n"
"    border-image: url(:/operation/简约1.jpg);\n"
"}")
        self.template_2 = QtWidgets.QWidget(Form)
        self.template_2.setGeometry(QtCore.QRect(0, 0, 1031, 741))
        self.template_2.setObjectName("template_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.template_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.label_9 = QtWidgets.QLabel(self.title)
        self.label_9.setGeometry(QtCore.QRect(20, 0, 978, 56))
        self.label_9.setStyleSheet("font: 22pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.title)
        self.section = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.section.sizePolicy().hasHeightForWidth())
        self.section.setSizePolicy(sizePolicy)
        self.section.setObjectName("section")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.section)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content = QtWidgets.QWidget(self.section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setObjectName("content")
        self.label = QtWidgets.QLabel(self.content)
        self.label.setGeometry(QtCore.QRect(115, 74, 731, 297))
        self.label.setStyleSheet("border-image: url(:/operation/实验结果图.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.design_instrument_btn1 = QtWidgets.QPushButton(self.content)
        self.design_instrument_btn1.setGeometry(QtCore.QRect(292, 82, 26, 24))
        self.design_instrument_btn1.setStyleSheet("border:12px solid red;\n"
"border-radius:12;\n"
"")
        self.design_instrument_btn1.setText("")
        self.design_instrument_btn1.setObjectName("design_instrument_btn1")
        self.design_instrument_btn3 = QtWidgets.QPushButton(self.content)
        self.design_instrument_btn3.setGeometry(QtCore.QRect(298, 131, 26, 24))
        self.design_instrument_btn3.setStyleSheet("border:12px solid red;\n"
"border-radius:12;\n"
"")
        self.design_instrument_btn3.setText("")
        self.design_instrument_btn3.setObjectName("design_instrument_btn3")
        self.design_instrument_btn2 = QtWidgets.QPushButton(self.content)
        self.design_instrument_btn2.setGeometry(QtCore.QRect(770, 80, 26, 24))
        self.design_instrument_btn2.setStyleSheet("border:12px solid red;\n"
"border-radius:12;\n"
"")
        self.design_instrument_btn2.setText("")
        self.design_instrument_btn2.setObjectName("design_instrument_btn2")
        self.design_instrument_btn4 = QtWidgets.QPushButton(self.content)
        self.design_instrument_btn4.setGeometry(QtCore.QRect(740, 133, 26, 24))
        self.design_instrument_btn4.setStyleSheet("border:12px solid red;\n"
"border-radius:12;\n"
"")
        self.design_instrument_btn4.setObjectName("design_instrument_btn4")
        self.pushButton_5 = QtWidgets.QPushButton(self.content)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 490, 26, 24))
        self.pushButton_5.setStyleSheet("border:12px solid red;\n"
"border-radius:12;\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.content)
        self.label_2.setGeometry(QtCore.QRect(120, 488, 71, 31))
        self.label_2.setStyleSheet("font: 14pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.content)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 440, 26, 24))
        self.pushButton_6.setStyleSheet("border:12px solid green;\n"
"border-radius:12;\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(self.content)
        self.label_3.setGeometry(QtCore.QRect(120, 440, 81, 31))
        self.label_3.setStyleSheet("font: 14pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.content)
        self.label_4.setGeometry(QtCore.QRect(765, 314, 101, 21))
        self.label_4.setStyleSheet("font: 12pt \"黑体\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.content)
        self.label_5.setGeometry(QtCore.QRect(865, 314, 91, 21))
        self.label_5.setStyleSheet("font: 12pt \"黑体\" ;\n"
"color: red;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.content)
        self.label_6.setGeometry(QtCore.QRect(765, 364, 221, 21))
        self.label_6.setStyleSheet("font: 12pt \"黑体\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.content)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.label_7.setStyleSheet("font: 16pt \"黑体\";")
        self.label_7.setObjectName("label_7")
        self.design_instrument_btn5 = QtWidgets.QPushButton(self.content)
        self.design_instrument_btn5.setGeometry(QtCore.QRect(561, 200, 26, 24))
        self.design_instrument_btn5.setStyleSheet("border:12px solid red;\n"
"border-radius:12;\n"
"")
        self.design_instrument_btn5.setObjectName("design_instrument_btn5")
        self.layoutWidget = QtWidgets.QWidget(self.content)
        self.layoutWidget.setGeometry(QtCore.QRect(520, 460, 264, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(80)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.designe_instrument_start_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.designe_instrument_start_btn.sizePolicy().hasHeightForWidth())
        self.designe_instrument_start_btn.setSizePolicy(sizePolicy)
        self.designe_instrument_start_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";\n"
"    background-color: green;\n"
"    color:rgb(255, 255, 255);\n"
"    width:91px;\n"
"    height:41px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";    \n"
"    background-color: green;\n"
"    color:green;\n"
"}")
        self.designe_instrument_start_btn.setObjectName("designe_instrument_start_btn")
        self.horizontalLayout.addWidget(self.designe_instrument_start_btn)
        self.design_instrument_stop_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.design_instrument_stop_btn_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.design_instrument_stop_btn_2.sizePolicy().hasHeightForWidth())
        self.design_instrument_stop_btn_2.setSizePolicy(sizePolicy)
        self.design_instrument_stop_btn_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";\n"
"    background-color: gray;\n"
"    color:rgb(255, 255, 255);\n"
"    width:91px;\n"
"    height:41px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";    \n"
"    background-color: gray;\n"
"    color:gray;\n"
"}")
        self.design_instrument_stop_btn_2.setObjectName("design_instrument_stop_btn_2")
        self.horizontalLayout.addWidget(self.design_instrument_stop_btn_2)
        self.label_8 = QtWidgets.QLabel(self.content)
        self.label_8.setGeometry(QtCore.QRect(750, 340, 221, 21))
        self.label_8.setStyleSheet("font: 14pt \"黑体\";\n"
"color: red;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.content)
        self.verticalLayout.addWidget(self.section)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "                           苯 乙 烯 阴 离 子 聚 合 实 验"))
        self.design_instrument_btn4.setText(_translate("Form", "、"))
        self.label_2.setText(_translate("Form", "关"))
        self.label_3.setText(_translate("Form", "开"))
        self.label_4.setText(_translate("Form", "当前压力："))
        self.label_5.setText(_translate("Form", "0  "))
        self.label_6.setText(_translate("Form", "压力要求：-240 至 -300"))
        self.label_7.setText(_translate("Form", "设计实验"))
        self.design_instrument_btn5.setText(_translate("Form", "、"))
        self.designe_instrument_start_btn.setText(_translate("Form", "开 始"))
        self.design_instrument_stop_btn_2.setText(_translate("Form", "停 止"))
        self.label_8.setText(_translate("Form", "通氮气操作"))
from views.images.operation_experiment_rc import *
