# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formula_calculate_one.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1047, 633)
        Form.setStyleSheet("#Form{\n"
"    \n"
"    border-image: url(:/calc/bj1.jpg);\n"
"}")
        self.template_2 = QtWidgets.QWidget(Form)
        self.template_2.setGeometry(QtCore.QRect(0, 0, 1051, 741))
        self.template_2.setObjectName("template_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.template_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.label_7 = QtWidgets.QLabel(self.title)
        self.label_7.setGeometry(QtCore.QRect(50, 10, 978, 56))
        self.label_7.setStyleSheet("font: 22pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.title)
        self.section = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.section.sizePolicy().hasHeightForWidth())
        self.section.setSizePolicy(sizePolicy)
        self.section.setObjectName("section")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.section)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content = QtWidgets.QWidget(self.section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    font: 16pt \"Arial\";\n"
"}\n"
"*{\n"
"    border-image:none;\n"
"}\n"
"QLineEdit {\n"
"    font: 12pt \"微软雅黑\";\n"
"    background-color:transparent;\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"}")
        self.content.setObjectName("content")
        self.label = QtWidgets.QLabel(self.content)
        self.label.setGeometry(QtCore.QRect(50, 50, 131, 31))
        self.label.setStyleSheet("font: 100 20pt \"Arial\";")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.content)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 120, 761, 360))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setStyleSheet("font: 16pt \"华文细黑\";")
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit.sizePolicy().hasHeightForWidth())
        self.LineEdit.setSizePolicy(sizePolicy)
        self.LineEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.LineEdit.setStyleSheet("QLineEdit :placeholderText{\n"
"    \n"
"    font: 11pt \"隶书\";\n"
"}\n"
"")
        self.LineEdit.setText("")
        self.LineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.LineEdit.setClearButtonEnabled(False)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_2.sizePolicy().hasHeightForWidth())
        self.Label_2.setSizePolicy(sizePolicy)
        self.Label_2.setStyleSheet("font: 16pt \"华文细黑\";")
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_2.sizePolicy().hasHeightForWidth())
        self.LineEdit_2.setSizePolicy(sizePolicy)
        self.LineEdit_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_3.sizePolicy().hasHeightForWidth())
        self.Label_3.setSizePolicy(sizePolicy)
        self.Label_3.setStyleSheet("font: 16pt \"华文细黑\";")
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_3.sizePolicy().hasHeightForWidth())
        self.LineEdit_3.setSizePolicy(sizePolicy)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_4.sizePolicy().hasHeightForWidth())
        self.Label_4.setSizePolicy(sizePolicy)
        self.Label_4.setStyleSheet("font: 16pt \"华文细黑\";")
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEdit_4.sizePolicy().hasHeightForWidth())
        self.LineEdit_4.setSizePolicy(sizePolicy)
        self.LineEdit_4.setStyleSheet("QLineEdit ::placeholderText{\n"
"    \n"
"    font: 14pt \"宋体\";\n"
"}")
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.tHFLabel = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tHFLabel.sizePolicy().hasHeightForWidth())
        self.tHFLabel.setSizePolicy(sizePolicy)
        self.tHFLabel.setStyleSheet("font: 16pt \"华文细黑\";")
        self.tHFLabel.setObjectName("tHFLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tHFLabel)
        self.tHFLineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tHFLineEdit.sizePolicy().hasHeightForWidth())
        self.tHFLineEdit.setSizePolicy(sizePolicy)
        self.tHFLineEdit.setObjectName("tHFLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tHFLineEdit)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("font: 12pt \"楷体\";\n"
"color:red;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("font: 12pt \"楷体\";\n"
"color:red;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("font: 12pt \"楷体\";\n"
"color:red;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("font: 12pt \"楷体\";\n"
"color:red;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font: 12pt \"楷体\";\n"
"color:red;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.calculate_one_submit_btn = QtWidgets.QPushButton(self.content)
        self.calculate_one_submit_btn.setGeometry(QtCore.QRect(860, 500, 91, 41))
        self.calculate_one_submit_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";\n"
"    background-color: rgb(31, 117, 213);\n"
"    color:rgb(255, 255, 255);\n"
"    width:91px;\n"
"    height:41px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";    \n"
"    background-color: rgb(31, 117, 213);\n"
"    color:rgb(31, 117, 213);\n"
"}")
        self.calculate_one_submit_btn.setObjectName("calculate_one_submit_btn")
        self.label_13 = QtWidgets.QLabel(self.content)
        self.label_13.setGeometry(QtCore.QRect(190, 56, 301, 21))
        self.label_13.setStyleSheet("font: 14pt \"楷体\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.content)
        self.verticalLayout.addWidget(self.section)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "                           苯 乙 烯 阴 离 子 聚 合 实 验"))
        self.label.setText(_translate("Form", "配方计算"))
        self.Label.setText(_translate("Form", "单体浓度"))
        self.LineEdit.setPlaceholderText(_translate("Form", "                                   %"))
        self.Label_2.setText(_translate("Form", "相对分子质量"))
        self.LineEdit_2.setPlaceholderText(_translate("Form", "                                   万"))
        self.Label_3.setText(_translate("Form", "总投料量"))
        self.LineEdit_3.setPlaceholderText(_translate("Form", "                                   g"))
        self.Label_4.setText(_translate("Form", "正丁基锂浓度"))
        self.LineEdit_4.setPlaceholderText(_translate("Form", "                                 mmol/ml"))
        self.tHFLabel.setText(_translate("Form", "[THF]/[活性中心]"))
        self.label_2.setText(_translate("Form", "(7~10)"))
        self.label_3.setText(_translate("Form", "(3万~6万)"))
        self.label_4.setText(_translate("Form", "15g~30g"))
        self.label_5.setText(_translate("Form", "0.7~1"))
        self.label_6.setText(_translate("Form", "1.7~2.3"))
        self.calculate_one_submit_btn.setText(_translate("Form", "确 认"))
        self.label_13.setText(_translate("Form", "(单位已给出,无须再带单位)"))
from views.images.calc_one_rc import *
