# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formula_calcualate_two.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1045, 627)
        Form.setStyleSheet("#Form{\n"
"    \n"
"    \n"
"    border-image:url(:/calc/bj1.jpg);\n"
"}")
        self.template_2 = QtWidgets.QWidget(Form)
        self.template_2.setGeometry(QtCore.QRect(0, 0, 1051, 741))
        self.template_2.setObjectName("template_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.template_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.label_9 = QtWidgets.QLabel(self.title)
        self.label_9.setGeometry(QtCore.QRect(50, 10, 978, 56))
        self.label_9.setStyleSheet("font: 22pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.title)
        self.section = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.section.sizePolicy().hasHeightForWidth())
        self.section.setSizePolicy(sizePolicy)
        self.section.setObjectName("section")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.section)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content = QtWidgets.QWidget(self.section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    font: 16pt \"Arial\";\n"
"}\n"
"*{\n"
"    border-image:none;\n"
"}\n"
"QLineEdit {\n"
"    font: 12pt \"微软雅黑\";\n"
"    background-color:transparent;\n"
"    border:none;\n"
"    border-bottom:1px solid rgb(255, 255, 255);\n"
"}\n"
"QLabel {\n"
"    font: 12pt \"华文细黑\";\n"
"}\n"
"#form QLabel{\n"
"    font: 13pt \"华文细黑\";\n"
"}\n"
"")
        self.content.setObjectName("content")
        self.label = QtWidgets.QLabel(self.content)
        self.label.setGeometry(QtCore.QRect(90, 50, 121, 31))
        self.label.setStyleSheet("font: 100 18pt \"Arial\";")
        self.label.setObjectName("label")
        self.form = QtWidgets.QWidget(self.content)
        self.form.setGeometry(QtCore.QRect(140, 250, 501, 181))
        self.form.setObjectName("form")
        self.formLayout = QtWidgets.QFormLayout(self.form)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.form)
        self.Label.setStyleSheet("")
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.form)
        self.LineEdit.setText("")
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.form)
        self.Label_2.setStyleSheet("")
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.form)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.Label_3 = QtWidgets.QLabel(self.form)
        self.Label_3.setStyleSheet("")
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.form)
        self.LineEdit_3.setStyleSheet("")
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.label_2 = QtWidgets.QLabel(self.content)
        self.label_2.setGeometry(QtCore.QRect(230, 58, 361, 21))
        self.label_2.setStyleSheet("font: 13pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.clacualate_two_submit_btn = QtWidgets.QPushButton(self.content)
        self.clacualate_two_submit_btn.setGeometry(QtCore.QRect(820, 460, 91, 41))
        self.clacualate_two_submit_btn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";\n"
"    background-color: rgb(31, 117, 213);\n"
"    color:rgb(255, 255, 255);\n"
"    width:91px;\n"
"    height:41px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:none;\n"
"    border-radius:7px;    \n"
"    font: 13pt \"微软雅黑\";    \n"
"    background-color: rgb(31, 117, 213);\n"
"    color:rgb(31, 117, 213);\n"
"}")
        self.clacualate_two_submit_btn.setObjectName("clacualate_two_submit_btn")
        self.label_3 = QtWidgets.QLabel(self.content)
        self.label_3.setGeometry(QtCore.QRect(650, 90, 121, 21))
        self.label_3.setStyleSheet("font: 14pt \"华文细黑\";")
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.content)
        self.layoutWidget.setGeometry(QtCore.QRect(700, 130, 271, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(22)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.Label_4.setStyleSheet("")
        self.Label_4.setObjectName("Label_4")
        self.verticalLayout_4.addWidget(self.Label_4)
        self.Label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.Label_5.setStyleSheet("")
        self.Label_5.setObjectName("Label_5")
        self.verticalLayout_4.addWidget(self.Label_5)
        self.Label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.Label_6.setStyleSheet("")
        self.Label_6.setObjectName("Label_6")
        self.verticalLayout_4.addWidget(self.Label_6)
        self.Label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.Label_7.setStyleSheet("")
        self.Label_7.setObjectName("Label_7")
        self.verticalLayout_4.addWidget(self.Label_7)
        self.tHFLabel = QtWidgets.QLabel(self.layoutWidget)
        self.tHFLabel.setStyleSheet("")
        self.tHFLabel.setObjectName("tHFLabel")
        self.verticalLayout_4.addWidget(self.tHFLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.content)
        self.verticalLayout.addWidget(self.section)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "                           苯 乙 烯 阴 离 子 聚 合 实 验"))
        self.label.setText(_translate("Form", "配方计算"))
        self.Label.setText(_translate("Form", "活性中心"))
        self.Label_2.setText(_translate("Form", "正丁基锂加入的毫升数为"))
        self.Label_3.setText(_translate("Form", "四氢呋喃加入的毫升数为"))
        self.label_2.setText(_translate("Form", "(结果保留两位有效数字,无须带单位)"))
        self.clacualate_two_submit_btn.setText(_translate("Form", "确 认"))
        self.label_3.setText(_translate("Form", "已知条件："))
        self.Label_4.setText(_translate("Form", "单体浓度"))
        self.Label_5.setText(_translate("Form", "相对分子质量"))
        self.Label_6.setText(_translate("Form", "总投料量"))
        self.Label_7.setText(_translate("Form", "正丁基锂浓度"))
        self.tHFLabel.setText(_translate("Form", "[THF]/[活性中心]"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "TextLabel"))
from views.images.calc_two_rc import *
