# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'get_styrene.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1033, 803)
        Form.setStyleSheet("#Form{\n"
                           "    \n"
                           "    border-image:url(:/add/bj3.jpeg);\n"
                           "}")
        self.template_2 = QtWidgets.QWidget(Form)
        self.template_2.setGeometry(QtCore.QRect(0, 0, 1031, 801))
        self.template_2.setObjectName("template_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.template_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.label_9 = QtWidgets.QLabel(self.title)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 978, 56))
        self.label_9.setStyleSheet("font: 24pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.title)
        self.section = QtWidgets.QWidget(self.template_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.section.sizePolicy().hasHeightForWidth())
        self.section.setSizePolicy(sizePolicy)
        self.section.setObjectName("section")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.section)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content = QtWidgets.QWidget(self.section)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setStyleSheet("")
        self.content.setObjectName("content")
        self.label_2 = QtWidgets.QLabel(self.content)
        self.label_2.setGeometry(QtCore.QRect(500, 340, 171, 332))
        self.label_2.setStyleSheet("border-image: url(:/add/广口瓶.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.content)
        self.label.setGeometry(QtCore.QRect(560, 90, 307, 307))
        self.label.setStyleSheet("border-image: url(:/add/注射器针管.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = syringe_label(self.content)
        self.label_3.setGeometry(QtCore.QRect(635, 120, 210, 212))
        self.label_3.setStyleSheet("border-image: url(:/add/注射器活塞.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.content)
        self.textBrowser.setGeometry(QtCore.QRect(30, 230, 431, 271))
        self.textBrowser.setStyleSheet("border:none;\n"
                                       "background-color: transparent;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.content)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 201, 101))
        self.label_4.setStyleSheet("font: 21pt \"楷体\";")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.content)
        self.label_7.setGeometry(QtCore.QRect(550, 670, 71, 41))
        self.label_7.setStyleSheet("border:none;\n"
                                   "background-color: transparent;\n"
                                   "font: 14pt \"等线\";")
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.content)
        self.layoutWidget.setGeometry(QtCore.QRect(710, 330, 161, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("border:none;\n"
                                   "background-color: transparent;\n"
                                   "font: 16pt \"等线\";\n"
                                   "color:red;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("border:none;\n"
                                   "background-color: transparent;\n"
                                   "font: 16pt \"等线\";\n"
                                   "color:red;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.content)
        self.label_8.setGeometry(QtCore.QRect(636, 290, 40, 40))
        self.label_8.setStyleSheet("border-image: url(:/add/填充png.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label.raise_()
        self.label_8.raise_()
        self.label_2.raise_()
        self.textBrowser.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.layoutWidget.raise_()
        self.label_3.raise_()
        self.verticalLayout_2.addWidget(self.content)
        self.verticalLayout.addWidget(self.section)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "                        苯 乙 烯 阴 离 子 聚 合 实 验"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">用注射器取约cmxml的样品，在cmx*0.9ml至cmx*1.1ml范围内为合格</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">注射器用法:</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">    用鼠标滑动注射器活塞将会抽取或排出药品</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "抽取苯乙烯"))
        self.label_7.setText(_translate("Form", "苯乙烯"))
        self.label_5.setText(_translate("Form", "当前:"))
        self.label_6.setText(_translate("Form", "0 ml"))


from views.ui.MyLabel import syringe_label
from views.images.add_styrene_rc import *
